# + ------------------------ +
# |       RealTimeSync       |
# |  Author: Edouard Courty  |
# + ------------------------ +

# World you want to change the time of
world: world

# Update rate (in game ticks, 20 ticks = 1 second)
update_rate: 80

# Forces the world to activate the doDayLightCycle gamerule that stops the time from changing by itself
# The default state of this gamerule in a world is true. Settings this to true will set it to false.
# Not enabling this can result in weird-looking sky at sunrise and sunset, since the sun will move before being updated.
force_daylightcycle_false: true

# Will spam the console. Makes the plugin log every time the in-game time is changed.
debug: false
